# 🔢 Project 1 - NumPy Data Explorer
**Syntecxhub Data Science Internship | Week 1**

---

## 📌 What is NumPy?
**NumPy (Numerical Python)** is the core library for numerical computing in Python.  
It introduces the `ndarray` - a fast, memory-efficient multi-dimensional array that outperforms standard Python lists for numerical operations.

### Why NumPy over Python lists?
| Feature | Python List | NumPy Array |
|---|---|---|
| Speed | Slow (loops) | Fast (vectorized) |
| Memory | High | Low (contiguous blocks) |
| Math ops | Manual | Built-in |
| Multi-dim | Nested lists | Native ndarray |

---

In [1]:
import numpy as np
import time
import sys

print(f"NumPy version: {np.__version__}")

NumPy version: 2.4.3


---
## 📦 Section 1: Array Creation
NumPy provides multiple ways to create arrays - from Python lists, built-in helpers, or random generators.

In [2]:
# --- From Python list ---
arr1d = np.array([10, 20, 30, 40, 50])
print(f"1D Array:   {arr1d}")
print(f"Shape:      {arr1d.shape}")
print(f"Data type:  {arr1d.dtype}")

# --- 2D Array (matrix) ---
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(f"\n2D Array (3x3):\n{arr2d}")
print(f"Shape: {arr2d.shape}  |  ndim: {arr2d.ndim}  |  dtype: {arr2d.dtype}")

1D Array:   [10 20 30 40 50]
Shape:      (5,)
Data type:  int64

2D Array (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)  |  ndim: 2  |  dtype: int64


In [3]:
# --- Built-in creation helpers ---
zeros = np.zeros((3, 3))              # all zeros
ones  = np.ones((2, 4))               # all ones
eye   = np.eye(3)                     # identity matrix
rng   = np.arange(0, 20, 2)           # like range(), returns array
linsp = np.linspace(0, 1, 5)          # 5 evenly spaced values between 0–1
rand  = np.random.randint(1, 100, size=(3, 3))  # random integers

print(f"zeros(3x3):\n{zeros}")
print(f"\nones(2x4):\n{ones}")
print(f"\nidentity(3x3):\n{eye}")
print(f"\narange(0,20,2):  {rng}")
print(f"linspace(0,1,5): {linsp}")
print(f"\nRandom 3x3 (1–99):\n{rand}")

zeros(3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

ones(2x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

identity(3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arange(0,20,2):  [ 0  2  4  6  8 10 12 14 16 18]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

Random 3x3 (1–99):
[[59 58 18]
 [94 35 51]
 [19 94 54]]


---
## 🔍 Section 2: Indexing & Slicing
NumPy uses `[row, col]` syntax for 2D arrays.  
- **Indexing**: access a specific element → `arr[1, 2]`
- **Slicing**: access a range → `arr[0:2, :]`
- **Boolean indexing**: filter by condition → `arr[arr > 50]`

In [4]:
data = np.array([[10,  20,  30,  40],
                 [50,  60,  70,  80],
                 [90, 100, 110, 120]])

print(f"Full array:\n{data}")
print(f"\nElement at row 1, col 2:   {data[1, 2]}")      # 70
print(f"First row:                 {data[0, :]}")        # [10 20 30 40]
print(f"Last column:               {data[:, -1]}")       # [40 80 120]
print(f"Top-left 2x2 block:\n{data[:2, :2]}")
print(f"Every other row:\n{data[::2, :]}")

# Boolean indexing
above_50 = data[data > 50]
print(f"\nAll values > 50: {above_50}")

Full array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element at row 1, col 2:   70
First row:                 [10 20 30 40]
Last column:               [ 40  80 120]
Top-left 2x2 block:
[[10 20]
 [50 60]]
Every other row:
[[ 10  20  30  40]
 [ 90 100 110 120]]

All values > 50: [ 60  70  80  90 100 110 120]


---
## 📊 Section 3: Mathematical & Statistical Operations
NumPy supports **element-wise**, **axis-wise**, and **aggregate** operations - all without writing a single loop.

- `axis=0` → operates **down columns** (per subject)
- `axis=1` → operates **across rows** (per student)

In [5]:
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [70, 65, 80]])
print(f"Student scores (3 students x 3 subjects):\n{scores}")

# Element-wise
print(f"\nScores + 5 bonus:\n{scores + 5}")
print(f"Scores * 1.1 (scaled):\n{np.round(scores * 1.1, 1)}")

# Axis-wise
print(f"\nMean per subject (axis=0): {scores.mean(axis=0)}")
print(f"Mean per student (axis=1): {scores.mean(axis=1)}")
print(f"Max per student:           {scores.max(axis=1)}")
print(f"Min per subject:           {scores.min(axis=0)}")
print(f"Sum of all scores:         {scores.sum()}")

Student scores (3 students x 3 subjects):
[[85 90 78]
 [92 88 95]
 [70 65 80]]

Scores + 5 bonus:
[[ 90  95  83]
 [ 97  93 100]
 [ 75  70  85]]
Scores * 1.1 (scaled):
[[ 93.5  99.   85.8]
 [101.2  96.8 104.5]
 [ 77.   71.5  88. ]]

Mean per subject (axis=0): [82.33333333 81.         84.33333333]
Mean per student (axis=1): [84.33333333 91.66666667 71.66666667]
Max per student:           [90 95 80]
Min per subject:           [70 65 78]
Sum of all scores:         743


In [6]:
# Overall statistical summary
flat = scores.flatten()
print("Overall Statistics:")
print(f"  Mean:            {flat.mean():.2f}")
print(f"  Median:          {np.median(flat):.2f}")
print(f"  Std Deviation:   {flat.std():.2f}")
print(f"  Min:             {flat.min()}")
print(f"  Max:             {flat.max()}")
print(f"  25th percentile: {np.percentile(flat, 25)}")
print(f"  75th percentile: {np.percentile(flat, 75)}")

Overall Statistics:
  Mean:            82.56
  Median:          85.00
  Std Deviation:   9.59
  Min:             65
  Max:             95
  25th percentile: 78.0
  75th percentile: 90.0


---
## 🔄 Section 4: Reshaping & Broadcasting
- **Reshaping**: change array dimensions without changing data → `reshape(3, 4)`
- **Broadcasting**: perform operations between arrays of *different shapes* - NumPy automatically expands the smaller array to match.

In [7]:
original = np.arange(1, 13)           # [1, 2, ..., 12]
print(f"Original 1D: {original}")

reshaped = original.reshape(3, 4)     # 3 rows × 4 cols
print(f"\nReshaped to (3, 4):\n{reshaped}")

reshaped_3d = original.reshape(2, 2, 3)
print(f"\nReshaped to (2, 2, 3):\n{reshaped_3d}")

flattened = reshaped.flatten()
print(f"\nFlattened back: {flattened}")

Original 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to (2, 2, 3):
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Flattened back: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
# Broadcasting: add a different bias to each column
matrix   = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
row_bias = np.array([10, 20, 30])     # shape (3,) → broadcasts across all rows

result = matrix + row_bias
print(f"Matrix:\n{matrix}")
print(f"\nRow bias:  {row_bias}")
print(f"\nMatrix + row_bias (broadcasting):\n{result}")
# col0+10, col1+20, col2+30 applied to every row

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row bias:  [10 20 30]

Matrix + row_bias (broadcasting):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


---
## 💾 Section 5: Save & Load NumPy Arrays
| Format | Function | Use case |
|---|---|---|
| `.npy` | `np.save / np.load` | Single array, fastest & lossless |
| `.npz` | `np.savez / np.load` | Multiple arrays in one file |
| `.csv` | `np.savetxt / np.loadtxt` | Human-readable, interoperable |

In [9]:
dataset = np.random.rand(5, 4)
print(f"Dataset to save (5x4):\n{np.round(dataset, 3)}")

# .npy — single array
np.save("student_scores.npy", dataset)
loaded_npy = np.load("student_scores.npy")
print(f"\nLoaded from .npy (row 0): {np.round(loaded_npy[0], 3)}")
print(f"Arrays match: {np.array_equal(dataset, loaded_npy)}")

# .npz — multiple arrays
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])
np.savez("multi_arrays.npz", array_a=a, array_b=b)
archive = np.load("multi_arrays.npz")
print(f"\nLoaded .npz — array_a: {archive['array_a']}")
print(f"Loaded .npz — array_b: {archive['array_b']}")

# .csv — text format
np.savetxt("scores_text.csv", dataset, delimiter=",", fmt="%.4f")
loaded_csv = np.loadtxt("scores_text.csv", delimiter=",")
print(f"\nLoaded from .csv (shape): {loaded_csv.shape}")

Dataset to save (5x4):
[[0.62  0.681 0.979 0.891]
 [0.86  0.957 0.23  0.787]
 [0.61  0.546 0.039 0.448]
 [0.256 0.61  0.548 0.052]
 [0.095 0.644 0.402 0.834]]

Loaded from .npy (row 0): [0.62  0.681 0.979 0.891]
Arrays match: True

Loaded .npz — array_a: [1 2 3]
Loaded .npz — array_b: [4 5 6]

Loaded from .csv (shape): (5, 4)


---
## ⚡ Section 6: NumPy vs Python Lists - Performance Comparison
This benchmark demonstrates the core reason NumPy exists - raw speed and memory efficiency.

In [10]:
SIZE = 1_000_000  # 1 million elements

# Python list
py_list = list(range(SIZE))
start = time.time()
py_sum = sum(py_list)
py_time = time.time() - start

# NumPy array
np_arr = np.arange(SIZE)
start = time.time()
np_sum = np_arr.sum()
np_time = time.time() - start

speedup = py_time / np_time if np_time > 0 else float('inf')

print(f"Task: sum of {SIZE:,} numbers")
print(f"Python list time:  {py_time:.5f}s")
print(f"NumPy array time:  {np_time:.5f}s")
print(f"NumPy is ~{speedup:.0f}x faster!")
print(f"\nMemory — Python list: {sys.getsizeof(py_list) / 1e6:.1f} MB")
print(f"Memory — NumPy array: {np_arr.nbytes / 1e6:.1f} MB")

Task: sum of 1,000,000 numbers
Python list time:  0.00425s
NumPy array time:  0.00046s
NumPy is ~9x faster!

Memory — Python list: 8.0 MB
Memory — NumPy array: 8.0 MB


---
## ✅ Summary

| Topic | Key Takeaway |
|---|---|
| Array Creation | `np.array`, `zeros`, `ones`, `arange`, `linspace`, `random` |
| Indexing & Slicing | `arr[row, col]`, boolean masks, step slicing |
| Math & Stats | Vectorized ops, `axis=0/1`, `mean`, `median`, `std`, `percentile` |
| Reshaping | `reshape()`, `flatten()`, broadcasting |
| Save/Load | `.npy`, `.npz`, `.csv` formats |
| Performance | NumPy is significantly faster and more memory-efficient than Python lists |

---
*Syntecxhub Data Science Internship - Week 1, Project 1*